### ISSUE TITLE
Bug: colors on charts re-sort on PDF export

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#61] opened 2019-12-12 03:10 UTC
Colors on this line chart are re-sorted and some manually added colors are kicked out. See recorded sample of this chart: https://app.datawrapper.de/chart/TxcWT/visualize#refine-the-chart
![colors switch at pdf export](https://user-images.githubusercontent.com/17730643/70679392-d03bed00-1c49-11ea-9720-54f05c4cd921.gif)

**Comment by palewire** [comment] 2019-12-24 21:47
I wonder if this bug is linked to #57

**Comment by palewire** [comment] 2020-01-03 18:34
I believe this is a duplicate of #63 and I am closing it.

**Closed by palewire** 2020-01-03 18:34 UTC
Labels: bug, print-theme
