### ISSUE TITLE
Web chart turns as grayscale print chart on PDF export selection

### ISSUE THREAD

**Issue by LElebee** [datadesk/datawrapper-migration#57] opened 2019-12-09 19:19 UTC
The PDF export tool appears to be exporting this chart as grayscale. Even though the option for grayscale would be great to have for print publication, how is this possible with this specific chart?
 https://app.datawrapper.de/chart/VDArY/visualize#refine-the-chart

The WEB style chart changes to a grayscale PRINT style chart when selecting PDF even though it may be set for RGB or even CMYK. 
When selecting the PRINT style, it also, converts it as grayscale in PDF selection. The PDF export is also grayscale, print style. 
![print turns grayscale](https://user-images.githubusercontent.com/17730643/70465423-cb264480-1a75-11ea-9c07-aa7ff66a5509.gif)
![web changes to grayscale print](https://user-images.githubusercontent.com/17730643/70465424-cb264480-1a75-11ea-88f6-7470d93ec03b.gif)
![color to grayscale](https://user-images.githubusercontent.com/17730643/70465426-cb264480-1a75-11ea-828d-059eb049135e.gif)

**Comment by elanals** [comment] 2019-12-10 14:30
Let me explain what is happening here:

You have two themes, with two different color palettes.

The web theme palette looks like this:

![image](https://user-images.githubusercontent.com/19191012/70537771-4c0e3a80-1b61-11ea-81fd-a3b7bede3204.png)

The print palette looks like this:

![image](https://user-images.githubusercontent.com/19191012/70537734-3f89e200-1b61-11ea-854a-2eda4bdb947c.png)

When you switch between themes, the color applied corresponds to the index of the selected color, in this case, it's the 8th color in the palette, which for the web theme is blue

![image](https://user-images.githubusercontent.com/19191012/70538085-cdfe6380-1b61-11ea-9d4b-35070ecd369a.png)

And for the print theme is grey:

![image](https://user-images.githubusercontent.com/19191012/70538111-d9ea2580-1b61-11ea-9ac5-022d73c8a211.png)

To avoid this kind of thing happening I would suggest that we align the print and web palettes, or that when switching to web, designers make sure to spend a moment to select the desired colors.

**Comment by elanals** [comment] 2019-12-10 14:31
For this reason, switching from the web theme to the print theme when the eight color is selected means that it changes from blue to grey.

**Comment by LElebee** [comment] 2020-01-02 19:26
It would be ideal if the colors were the same for both print and web. I think we initially wanted to use the print colors for web. So the order of the colors should be the same for both web and print. >> For choropleth map colors, we have color range palettes. I can pass along the color combinations.

**Comment by palewire** [comment] 2020-01-03 18:28
I looks to me that this ticket is a duplicate of #63. Let's close this to consolidate our requests.

**Closed by palewire** 2020-01-03 18:28 UTC
Labels: bug, print-theme, web-theme
